export const ADVERTENCIA = {
  CUOTA_SOCIAL_IMPAGA: 'CUOTA_SOCIAL_IMPAGA',
  CUOTA_IMPAGA: 'CUOTA_IMPAGA',
  LIMITE_SEMANAL: 'LIMITE_SEMANAL',
  PASE_MENSUAL_IMPAGO: 'PASE_MENSUAL_IMPAGO',
  MOROSIDAD_CUOTA_SOCIAL: 'MOROSIDAD_CUOTA_SOCIAL',
};
