import express from 'express';
import authRoutes from './resources/usuarios/routes.js';
import staffRoutes from './resources/usuarios/staffRoutes.js';
import socioRoutes from './resources/socios/routes.js';
import movimientoRoutes from './resources/movimientos/routes.js';
import cobroRoutes from './resources/cobros/routes.js';
import muroLibreRoutes from './resources/muroLibre/routes.js';
import escuelitaRoutes from './resources/escuelita/routes.js';
import asistenciasRoutes from './resources/asistencias/routes.js';
import novedadesRoutes from './resources/novedades/routes.js';
import horariosRoutes from './resources/horarios/routes.js';
import preciosRoutes from './resources/cuotas/preciosRoutes.js';
import etiquetasRoutes from './resources/etiquetas/routes.js';
import suscripcionesRoutes from './resources/suscripciones/routes.js';
import exportRoutes from './resources/export/routes.js';
import auditRoutes from './resources/audit/routes.js';
import rolesRoutes from './resources/roles/routes.js';
import superRoutes from './resources/super/routes.js';
import planesRoutes from './resources/planes/routes.js';
import advertenciasRoutes from './resources/advertencias/routes.js';
import formsWebhookRoutes from './resources/formsWebhook/routes.js';
import notificacionesRoutes from './resources/notificaciones/routes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/usuarios/staff', staffRoutes);
router.use('/socios', socioRoutes);
router.use('/movimientos', movimientoRoutes);
router.use('/cobros', cobroRoutes);
router.use('/muro-libre', muroLibreRoutes);
router.use('/escuelita', escuelitaRoutes);
router.use('/asistencias', asistenciasRoutes);
router.use('/novedades', novedadesRoutes);
router.use('/horarios', horariosRoutes);
router.use('/precios', preciosRoutes);
router.use('/etiquetas', etiquetasRoutes);
router.use('/suscripciones', suscripcionesRoutes);
router.use('/export', exportRoutes);
router.use('/audit', auditRoutes);
router.use('/roles', rolesRoutes);
router.use('/super', superRoutes);
router.use('/planes', planesRoutes);
router.use('/advertencias', advertenciasRoutes);
router.use('/forms-webhook', formsWebhookRoutes);
router.use('/notificaciones', notificacionesRoutes);

export default router;
